### ISSUE TITLE
Setup website

### ISSUE THREAD

**Issue by geekle** [devopsaustralia/general#11]
- Define what is Devops Australia
- Define who is Devops Australia
- Contact page (including press information)

**Comment by auxesis** [comment]
I've attempted to re-register devops.org.au

Waiting on approval from the registry.

**Comment by auxesis** [comment]
Still waiting, double checking now.

**Comment by auxesis** [comment]
The domain has been paid for with [iWantMyName](https://iwantmyname.com/), but it doesn't appear to be registered. 
- [ ] @auxesis to chase up iWantMyName on why the domain isn't registered

**Comment by auxesis** [comment]
Have pinged iWantMyName, waiting for a response.

**Comment by auxesis** [comment]
Got a response. 

I tried registering devops.org.au, but because we don't have an ABN, I used the ABN for my sole tradership. 

Apparently registrars will happily register a .org.au for you, however AUDA will come audit it, and simply delete the registration if they don't think you qualify for the domain. 

The best part is they won't notify the registrar that they've actually deleted the domain, so the registrar will happily collect money from the person registering the domain, but never refund them because they have no idea the domain has been de-registered. 

I checked and provided I have a valid ABN that links back to DevOps Australia Inc, the domain should register fine.

**Comment by auxesis** [comment]
Once we've got the ABN per #9, I should be good to register the domain.

**Comment by geekle** [comment]
:+1:

**Comment by auxesis** [comment]
Now we have the ABN, going to re-apply now.

**Comment by auxesis** [comment]
Applied, waiting on a response.

**Comment by auxesis** [comment]
It got rejected again. 

No reason given. I'm going to chase this today.

**Comment by auxesis** [comment]
Our registration [is public now](http://abr.business.gov.au/SearchByAbn.aspx?abn=35167927157).

**Comment by auxesis** [comment]
Have pinged iWantMyName, waiting for a response.

**Comment by auxesis** [comment]
The domain is now registered. [devops.org.au](http://devops.org.au) points to GitHub pages. 

![image](https://cloud.githubusercontent.com/assets/12306/3885903/3000bb3e-21ce-11e4-9b97-d9dc9c8166b5.png)

**Comment by auxesis** [comment]
@devopsaustralia/owners what content do we want to see on the site?
- Purpose (to provide financial aid to the devops and related communities in Australia)
- Who is behind it
- How to get reimbursed
- What events we help

**Comment by auxesis** [comment]
This is now set up at https://devops.org.au/
